// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQy21ML5IAdiXRSXD1crIAmYc_tTn8M4c',
    appId: '1:1095542040327:web:5806d10c77e897728147a2',
    messagingSenderId: '1095542040327',
    projectId: 'campuseats-vvu',
    authDomain: 'campuseats-vvu.firebaseapp.com',
    storageBucket: 'campuseats-vvu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVxIJoeXgAaNyeZLmkmSkx3P6p_GsZD0g',
    appId: '1:1095542040327:android:7d3241bd552e72b58147a2',
    messagingSenderId: '1095542040327',
    projectId: 'campuseats-vvu',
    storageBucket: 'campuseats-vvu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBReUAROzoQbWmfHkNo04NDBctXciI5GT4',
    appId: '1:1095542040327:ios:2d1476c2ecf56d828147a2',
    messagingSenderId: '1095542040327',
    projectId: 'campuseats-vvu',
    storageBucket: 'campuseats-vvu.firebasestorage.app',
    iosBundleId: 'com.example.inft425CampusEatBright',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBReUAROzoQbWmfHkNo04NDBctXciI5GT4',
    appId: '1:1095542040327:ios:2d1476c2ecf56d828147a2',
    messagingSenderId: '1095542040327',
    projectId: 'campuseats-vvu',
    storageBucket: 'campuseats-vvu.firebasestorage.app',
    iosBundleId: 'com.example.inft425CampusEatBright',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQy21ML5IAdiXRSXD1crIAmYc_tTn8M4c',
    appId: '1:1095542040327:web:8856d6cb5eb6488c8147a2',
    messagingSenderId: '1095542040327',
    projectId: 'campuseats-vvu',
    authDomain: 'campuseats-vvu.firebaseapp.com',
    storageBucket: 'campuseats-vvu.firebasestorage.app',
  );
}
